trigger: 
 - master

strategy:
  matrix:
    linux:
      imageName: ubuntu-18.04
    mac:
      imageName: macos-10.15
    windows:
      imageName: windows-2019

pool:
  vmImage: $(imageName)

steps: 
- task: GoTool@0
  displayName: 'Use Go 1.14.2'
  inputs:
    version: '1.14.2'
- task: Go@0
  displayName: 'go get'
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- script: 'go test -v -cover ./...'
  displayName: 'go test'